name: 
CI
on:
push:
branches:
- main

jobs:
lint:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Lint Step
run: echo "Hello world"

test:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Test Step
run: echo "Hello world"

test1:
strategy:
matrix:
os:
- ubuntu-latest
- windows-latest
- macos-latest
runs-on: ${{ matrix.os }}
steps:
- uses: actions/checkout@v4
- name: Matrix Test
run: echo "hello Test"

publish:
runs-on: ubuntu-latest
needs: [lint, test]
steps:
- uses: actions/checkout@v4
- name: Publish Step
run: echo "Hello world"
